### PR TITLE
Replace abandoned Sensiolabs security checker

### PR DESCRIPTION
**Pull request by paras-malhotra**
This PR replaces the abandoned [Sensiolabs security checker](https://github.com/sensiolabs/security-checker) with the [Enlightn security checker](https://github.com/enlightn/security-checker).

### CODE REVIEW

**Comment by paras-malhotra** [comment]
This PR has several advantages over https://github.com/EdgedesignCZ/phpqa/pull/214:
1. The Enlightn security checker is licensed under MIT so it can be used in any app. The other PR uses local php security checker which is licensed under AGPLv3, and thus cannot be used by any non-AGPL app.
2. This Enlightn security checker can be pulled in via composer whereas the local-php-security-checker needs to download binaries. This depends on system architecture and needs hacky solutions / shell scripts to make it work.

**Comment by zdenekdrahos** [comment]
Looks interesting. Composer.lock is not uploaded anywhere, am I correct?

**Comment by paras-malhotra** [comment]
That's right @zdenekdrahos, it just looks for the lock file in the current directory. It's very similar to how the old Sensiolabs security-checker worked.

**Comment by zdenekdrahos** [comment]
Could you support `symfony/finder:2`? I'd like to keep support for older php and symfony versions.

> https://travis-ci.org/github/EdgedesignCZ/phpqa/jobs/756550442#L596
> enlightn/security-checker v1.3 requires symfony/finder ^3|^4|^5 but these conflict with your requirements or minimum-stability.

**Comment by paras-malhotra** [comment]
Hey @zdenekdrahos, I've added support all the way upto PHP 5.6 with https://github.com/enlightn/security-checker/pull/6. We need a min of symfony/yaml 3.4 and symfony/console 3.4 for everything to work right now. 

Given that 5.6 was EOL in 2018, I think it's a good version to support for now. I'm open to PRs for expanding support though but this as far as I can get for now. Hope that works!

**Pull request merged**
