### PR TITLE
phpcpd v6 support

### PR DESCRIPTION
**Pull request by xaben**
Take into consideration dropped/renamed CLI arguments from:

https://github.com/sebastianbergmann/phpcpd/blob/6.0.2/ChangeLog.md

### CODE REVIEW

**Comment by xaben** [comment]
I assume we would need to enforce phpcpd version > 6 in composer?

**Comment by masterjus** [comment]
`progress` could be replaced to `verbose`

**Comment by ndench** [comment]
Anything I can do to help this get merged?

**Comment by zdenekdrahos** [comment]
It's BC for older phpcpd versions. Its' going to be fixed in https://github.com/EdgedesignCZ/phpqa/pull/218/commits/f7c2998f10c8008d4a02ea3be4d9a52de1d8398f

**Pull request closed without merging**
