### PR TITLE
phpmetrics will generate violations xml report

### PR DESCRIPTION
**Pull request by thinkspill**
From the phpmetrics docs: PhpMetrics can export results in the PhpMessDetector violations output format.

This adds the flag to create the violations xml.

### CODE REVIEW

**Comment by zdenekdrahos** [comment]
What's the difference between phpmetrics violations and [phpmd violations](https://phpmd.org/documentation/index.html)? phpmd is well documented and ruleset can be overriden. I can't find anything about violations in phpmetrics.

**Comment by thinkspill** [comment]
I believe it's just outputting it's own collected data in the phpmd violations xml format, not specifically outputting phpmd data (and I could be wrong about that as the docs aren't specific either way). Here's where I found the info: http://www.phpmetrics.org/documentation/jenkins.html

In any case, users can choose to utilize the outputted file or not. I'm still experimenting with it to see if it is especially better or different than the output from the real phpmd.

**Comment by zdenekdrahos** [comment]
I don't want to generate some file, just because tool can generate it. I wrote about that in https://github.com/EdgedesignCZ/phpqa/pull/17#issuecomment-214136398

Users can define [phpmd' ruleset](https://github.com/EdgedesignCZ/phpqa/blob/master/.phpqa.yml#L17). Why should we confuse them with two `pmd` xml files? For example Jenkins can parse violations only from one file:

screen shot 2016-05-10 at 14 36 02

Isn't possible to define custom ruleset for phpmd with phpmetrics' rules? I would rather add notice to readme about phpmetrics ruleset than generate two pmd files

**Comment by thinkspill** [comment]
Sure, makes sense. I'll let you know if I find any additional details that would warrant including this. Thanks!

**Pull request closed without merging**
